name: Sync with GitHub Enterprise
env:
  GITHUB_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
  GHE_USER: ${{ vars.SYNC_USER }}
  GHE_FULL_USER: ${{ vars.SYNC_USER_NAME }}
  ENTERPRISE_URL: ${{ vars.ENTERPRISE_GIT_URL }}
  ENTERPRISE_EMAIL: ${{ vars.SYNC_USER_EMAIL }}
  DEFAULT_TEMPLATE: ${{ vars.REPO_TEMPLATE }}

on:
  push:
    branches:
      - '*'
      
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if remote enterprise repo exists
        id: repocheck
        run: git ls-remote https://${{ env.GHE_USER }}:${{ env.GITHUB_TOKEN }}@${{ env.ENTERPRISE_URL }}/${{ github.repository }} -q --exit-code
      - name: Create remote repo
        if: ${{ failure() && steps.repocheck.conclusion == 'failure' }}
        run: |
          echo ${{ env.GITHUB_TOKEN }} > /tmp/token.txt
          gh auth login -p https -h ${{ env.ENTERPRISE_URL }} --with-token < /tmp/token.txt
          gh repo create --public ${{ github.repository }}
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and all branches to stage
        if: ${{ github.repository != env.DEFAULT_TEMPLATE }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Push the repo up to our internal github
#        if: ${{ github.repository != env.DEFAULT_TEMPLATE }}
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://${{ env.ENTERPRISE_URL }}/${{ github.repository }}'
          GIT_USERNAME: ${{ env.GHE_USER }}
          GIT_PASSWORD: ${{ env.GITHUB_TOKEN }}
